services:
  app:
    build: .
    container_name: partymanager-app
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - partymanager_data:/app/resources
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3001}/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - partymanager-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "com.docker.compose.project=partymanager"
      - "com.docker.compose.service=app"

networks:
  partymanager-network:
    driver: bridge

volumes:
  partymanager_data:
    name: partymanager_data