services:
  app:
    build: .
    container_name: partymanager-app
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    volumes:
      - partymanager_data:/app/resources
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - DOMAIN_URL=${DOMAIN_URL}
      - PORT=${PORT:-3001}
      - API_URL=${API_URL:-/web-app-api}
      - WEBHOOK_URL=${WEBHOOK_URL:-/webhook}
      - MENU_BUTTON_URL=${MENU_BUTTON_URL:-/}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3001}/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - partymanager-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.partymanager.rule=Host(`jhartum.work.gd`) && PathPrefix(`/partymanager`)"
      - "traefik.http.routers.partymanager.entrypoints=websecure"
      - "traefik.http.routers.partymanager.tls.certresolver=myresolver"
      - "traefik.http.middlewares.partymanager-stripprefix.stripprefix.prefixes=/partymanager"
      - "traefik.http.routers.partymanager.middlewares=partymanager-stripprefix@docker"
      - "traefik.http.services.partymanager.loadbalancer.server.port=${PORT:-3001}"
      - "com.docker.compose.project=partymanager"
      - "com.docker.compose.service=app"

networks:
  partymanager-network:
    driver: bridge

volumes:
  partymanager_data:
    name: partymanager_data